linter:
  rules:
  - avoid_empty_else
  - avoid_field_initializers_in_const_classes
  - avoid_function_literals_in_foreach_calls
  - avoid_js_rounded_ints
  - avoid_null_checks_in_equality_operators
  - avoid_relative_lib_imports
  - avoid_returning_null_for_future
  - avoid_slow_async_io
  - avoid_types_as_parameter_names
  - avoid_unused_constructor_parameters
  - cancel_subscriptions
  - close_sinks
  - control_flow_in_finally
  - curly_braces_in_flow_control_structures
  - directives_ordering
  - empty_statements
  - hash_and_equals
  - invariant_booleans
  - iterable_contains_unrelated_type
  - literal_only_boolean_expressions
  - no_adjacent_strings_in_list
  - no_duplicate_case_values
  - null_closures
  - prefer_const_constructors
  - prefer_const_constructors_in_immutables
  - prefer_const_declarations
  - prefer_const_literals_to_create_immutables
  - prefer_contains
  - prefer_final_fields
  - prefer_final_in_for_each
  - prefer_final_locals
  - prefer_foreach
  - prefer_is_not_empty
  - prefer_null_aware_operators
  - prefer_single_quotes
  - prefer_spread_collections
  - prefer_void_to_null
  - unawaited_futures
  - unnecessary_await_in_return
  - unnecessary_brace_in_string_interps
  - unnecessary_lambdas
  - unnecessary_new
  - unnecessary_statements
  - unnecessary_this
  - use_string_buffers
  - use_to_and_as_if_applicable