name: pingis
description: Pingis flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Business logic
  equatable: ^0.3.0
  flutter_bloc: ^0.20.0
  get_it: 1.0.3+2
  provider: ^3.0.0+1
  rxdart: ^0.22.1

  # Firebase & Authentication
  firebase_analytics: ^4.0.2
  firebase_auth: ^0.14.0
  firebase_core: ^0.4.0+1

  cloud_firestore: ^0.12.9
  google_sign_in: ^4.0.4

  # UI related

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: RussoOne
      fonts:
        - asset: fonts/RussoOne-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

